# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" , "develop"]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: read # for checkout

jobs:
  release:
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm clean-install
      - name: Release
        run: npm run semantic-release
  merge_release:
    needs: [release]
    runs-on: ubuntu-20.04
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    env:
      FROM_BRANCH: main
      TO_BRANCH: develop
      USER_NAME: Github Actions
      USER_MAIL: actions@github.com
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"

      - name: Merge dev back to develop
        run: |
          git fetch --depth=5
          git checkout develop
          git pull
          git merge --no-ff main -m "Auto-merge master back to develop"
          git push